name: Build and deploy Node.js app to Azure Web App - avans-programmeren-4

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Install and build
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'

            - name: npm install, build, and test
              run: |
                  npm install

            - name: Zip artifact for deployment
              run: zip release.zip ./* -r

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                    name: node-app
                    path: release.zip

    #performancetest:
     #   runs-on: ubuntu-latest
      #  needs: build
       # name: Load test with Artillery
        #steps:
         #   - name: Download artifact from build job
          #    uses: actions/download-artifact@v4
           #   with:
            #      name: node-app

            #- name: Unzip artifact for tests
            #  run: unzip release.zip

           # - name: Execute load tests
            #  uses: artilleryio/action-cli@v1
             # with:
              #    command: run perftest.yml

    integrationtests:
        runs-on: ubuntu-latest
        needs: build
        name: Integration tests with MySQL Db
        env:
            MYSQL_ROOT_PASSWORD: root
            DB_HOST: 127.0.0.1
            DB_PORT: 3306
            DB_DATABASE: share_a_meal
            DB_USER: root
            DB_PASSWORD: root
            PORT: 3000
        services:
            mysql:
                image: mysql:8.0
                ports:
                - 3306

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Unzip artifact for tests
              run: unzip release.zip

            - name: Start MySQL connection from host
              run: |
                  sudo /etc/init.d/mysql start
                  sudo apt-get install -y mysql-client
                  mysql -h 127.0.0.1 -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "SHOW DATABASES;"
                  mysql -h 127.0.0.1 -uroot -p${{ env.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE ${{env.DB_DATABASE}};"

            - name: Import the database
              run: |
                  mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}} ${{env.DB_DATABASE}} < share-a-meal.sql
                  mysql -uroot -p${{env.MYSQL_ROOT_PASSWORD}} ${{env.DB_DATABASE}} -e "SHOW TABLES;"

            - name: npm test
              run: |
                  npm test -- --DB_PASSWORD $MYSQL_ROOT_PASSWORD --DB_USER root --DB_NAME $DB_DATABASE --DB_PORT $DB_PORT

    deploy:
        runs-on: ubuntu-latest
        needs: [integrationtests]
        name: Deploy to Azure Web App
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Unzip artifact for deployment
              run: unzip release.zip -d release

            - name: 'Login via Azure CLI'
              run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
              #uses: azure/login@v1
              #with:
               # environment: 'azurecloud'
                
                #tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                #client-id: ${{ secrets.AZURE_CLIENT_ID }}
                #subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
                #auth-type: 'SERVICE_PRINCIPAL' 

                
          
                


            - name: 'Deploy to Azure Web App'
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                app-name: 'share-a-meal-amin'
                slot-name: 'Production'
                package: ./release
