name: Build, Test & Deploy Node.js App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install and build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Zip artifact
        run: zip release.zip ./* -r

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  integrationtests:
    runs-on: ubuntu-latest
    needs: build
    name: Integration tests with MySQL
    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_DATABASE: share-a-meal
      MYSQL_ROOT_PASSWORD: root
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: share-a-meal
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Install MySQL client
        run: sudo apt-get install -y mysql-client

      - name: Wait for DB to be ready
        run: |
          echo "Waiting for MySQL..."
          until mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; do
            sleep 2
          done

      - name: Import test database
        run: |
          if [ -f share-a-meal.sql ]; then
            mysql -h 127.0.0.1 -uroot -proot share-a-meal < share-a-meal.sql
          else
            echo "⚠ No share-a-meal.sql found, skipping DB import."
          fi

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [integrationtests]
    name: Deploy to Azure Web App
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip -d release

      - name: Deploy to Azure Web App via Publish Profile
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'programmeren-4'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./release


      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'programmeren-4'
          slot-name: 'Production'
          package: ./release
